name: React Frontend CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v4

      # 2. Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '22'

      # 3. Install dependencies & build
      - name: Install & Build
        run: |
          npm install
          npm run build

      # 4. Deploy to Azure Web App
      - uses: azure/webapps-deploy@v2
        with:
          app-name: restaurant-cloud-frontend   # Your Azure App Name
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./build
