name: Node.js CI/CD

on:
  push:
    branches: [ main ]  # Runs on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repository
      - uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # 3. Install dependencies (backend folder)
      - name: Install dependencies
        working-directory: restaurant-backend
        run: npm install

      # 4. Optional: Run tests
      - name: Run tests
        working-directory: restaurant-backend
        run: npm test || echo "No tests defined"

      # 5. Azure Login using Service Principal
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            }

      # 6. Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: restaurant-cloud-backend   # Your Azure Web App name
          slot-name: production
          package: ./restaurant-backend
