name: Build and deploy React app to Azure Web App - restaurant-cloud-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        working-directory: restaurant-frontend
        run: npm install

      - name: Build frontend
        working-directory: restaurant-frontend
        run: npm run build

      - name: Zip build folder
        working-directory: restaurant-frontend
        run: zip -r build.zip build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: restaurant-frontend/build.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: react-build
          path: build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy React build zip to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'restaurant-cloud-frontend'
          package: build/build.zip
