name: Build and deploy React app to Azure Web App - restaurant-cloud-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1️⃣ Checkout repository
      - uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # 3️⃣ Install frontend dependencies
      - name: Install dependencies
        working-directory: restaurant-frontend
        run: npm install

      # 4️⃣ Build React frontend
      - name: Build frontend
        working-directory: restaurant-frontend
        run: npm run build

      # 5️⃣ Upload build artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: restaurant-frontend/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      id-token: write

    steps:
      # 1️⃣ Download build artifact
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: react-build

      # 2️⃣ Azure login using Service Principal
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      # 3️⃣ Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'restaurant-cloud-frontend'
          slot-name: 'Production'
          package: restaurant-frontend/build
