name: Node.js CI/CD

on:
  push:
    branches: [ main ]  # Trigger workflow on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # 3. Install backend dependencies (including required packages)
      - name: Install backend dependencies
        working-directory: restaurant-backend
        run: |
          npm install
          npm install bcrypt @azure/storage-blob multer dotenv uuid

      # 4. Optional: Run backend tests
      - name: Run backend tests
        working-directory: restaurant-backend
        run: npm test || echo "No tests defined"

      # 5. Azure Login using Service Principal
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            }

      # 6. Deploy backend to Azure Web App
      - name: Deploy Backend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: restaurant-cloud-backend  # Your Azure Web App name
          slot-name: production
          package: ./restaurant-backend
          working-directory: restaurant-backend

